# Generated by Django 3.2.7 on 2021-09-10 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='', verbose_name='Profile Picture')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('state', models.CharField(max_length=40, verbose_name='State')),
                ('zip', models.CharField(max_length=30, verbose_name='Zip Code')),
                ('phone_number', models.CharField(blank=None, max_length=12, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=None, max_length=12, unique=True)),
                ('profile_img', models.ImageField(upload_to='', verbose_name='Profile Picture')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('state', models.CharField(max_length=40, verbose_name='State')),
                ('zip', models.CharField(max_length=30, verbose_name='Zip Code')),
                ('name', models.CharField(blank=None, max_length=100, unique=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True, unique=True)),
                ('type', models.CharField(choices=[('C', 'Company'), ('P', 'Person'), ('O', 'Other')], max_length=9, verbose_name='Provider type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=1, verbose_name='Package size')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('name', models.CharField(max_length=100)),
                ('available', models.IntegerField(default=0, verbose_name='Available packages')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provider')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.package_type', verbose_name='Package type')),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=None, max_length=12, unique=True)),
                ('profile_img', models.ImageField(upload_to='', verbose_name='Profile Picture')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('state', models.CharField(max_length=40, verbose_name='State')),
                ('zip', models.CharField(max_length=30, verbose_name='Zip Code')),
                ('first_name', models.CharField(blank=None, max_length=30)),
                ('last_name', models.CharField(blank=None, max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('id_card_img', models.ImageField(upload_to='', verbose_name='Identity Card Image')),
                ('num_wives', models.IntegerField(default=0, verbose_name='Number of wives')),
                ('num_children', models.IntegerField(default=0, verbose_name='Number of Children')),
                ('id_card_num', models.IntegerField(unique=True)),
                ('num_packages', models.IntegerField(unique=True, verbose_name='Number of packages received')),
                ('provided_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
