# Generated by Django 3.2.7 on 2021-11-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210911_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'ordering': ['-provided_at']},
        ),
        migrations.AlterField(
            model_name='consumer',
            name='first_name',
            field=models.SlugField(blank=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='gender',
            field=models.SlugField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='last_name',
            field=models.SlugField(blank=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='phone_number',
            field=models.SlugField(blank=None, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='subscription_status',
            field=models.SlugField(choices=[('A', 'Active'), ('P', 'Pending'), ('S', 'Suspended')], max_length=1, verbose_name='Subscription Status'),
        ),
        migrations.AlterField(
            model_name='package',
            name='size',
            field=models.SlugField(max_length=1, verbose_name='Package size'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='gender',
            field=models.SlugField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.SlugField(blank=None, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='gender',
            field=models.SlugField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.SlugField(blank=None, max_length=12, unique=True),
        ),
    ]
