# Generated by Django 3.2.7 on 2021-11-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211113_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='profile_img',
            field=models.ImageField(blank=None, null=True, upload_to='consumers/img/profile_img/', verbose_name='Profile Picture'),
        ),
    ]
