# Generated by Django 3.2.7 on 2021-11-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_consumer_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='city',
            field=models.CharField(blank=True, max_length=40, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='first_name',
            field=models.CharField(blank=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='last_name',
            field=models.CharField(blank=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='phone_number',
            field=models.CharField(blank=None, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='consumers/img/profile_img/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='state',
            field=models.CharField(blank=True, max_length=40, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='zip',
            field=models.CharField(blank=True, max_length=30, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.CharField(blank=True, max_length=40, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=None, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.CharField(blank=True, max_length=40, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='zip',
            field=models.CharField(blank=True, max_length=30, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='city',
            field=models.CharField(blank=True, max_length=40, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.CharField(blank=None, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='users/img/profile_img/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='state',
            field=models.CharField(blank=True, max_length=40, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='zip',
            field=models.CharField(blank=True, max_length=30, verbose_name='Zip Code'),
        ),
    ]
