# Generated by Django 3.2.7 on 2021-11-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211115_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.consumer', verbose_name='Responsale'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='is_responsable',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
