# Generated by Django 3.2.7 on 2021-11-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211116_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.consumer', verbose_name='Responsable'),
        ),
    ]
