# Generated by Django 3.2.7 on 2021-12-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_consumer_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='gender',
            field=models.SlugField(max_length=1),
        ),
        migrations.AlterField(
            model_name='provider',
            name='gender',
            field=models.SlugField(max_length=1),
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
