# Generated by Django 3.2.7 on 2021-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211215_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
