# Generated by Django 3.2.7 on 2021-12-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211216_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.consumer', verbose_name='Responsable'),
        ),
    ]
