# Generated by Django 3.2.7 on 2021-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211213_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Is Verified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='cover_img',
            field=models.ImageField(blank=True, default='default/img/cover_img/1.jpg', null=True, upload_to='users/img/cover_img/', verbose_name='Cover Picture'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='default/img/profile_img/1.png', null=True, upload_to='users/img/profile_img/', verbose_name='Profile Picture'),
        ),
    ]
