# Generated by Django 3.2.7 on 2021-12-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20211216_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
